apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: integration-server-poc
  namespace: cp4i
spec:
  adminServerSecure: true
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: L-KSBM-C5JEHP
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  version: '11.0.0.14-r1-eus'
  barURL: >-
    https://localhost:8081/repository/integration/Rest_Api_Application_Put_Get.bar
