name: UBA_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

      
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Building bar file
        env: 
           BAR_CREATION: /opt/ace-11.0.0.7/tools/mqsicreatebar
           BAR_STORE: /home/bandaru/Templates
        run: |
            $BAR_CREATION -data /root -b $BAR_STORE/Rest_Api_Application_Put_Get.bar -a Rest_Api_Application_Put_Get
      - name: Publishing_Artifacts
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }} 
          NEXUS_REPOSITORY_URL: ${{ secrets.NEXUS_REPOSITORY_URL }}
        run:  curl -v -u$NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file $BAR_STORE/Rest_Api_Application_Put_Get.bar  $NEXUS_REPOSITORY_URL      
             
      - name: oc login
        run: |
             cd /usr/local/bin/ 
             ./oc login --token=sha256~BPsuJLVUsxnpAgLbwYg10egcmDfqWoJklnPZuA847sY --server=https://c104-e.us-east.containers.cloud.ibm.com:31739
             ./oc project cp4i
             ./oc create -f /root/cp4i.yaml
