name: UBA_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

      
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Building bar file
        env: 
           BAR_CREATION: /opt/ace-11.0.0.7/tools/mqsicreatebar
           BAR_STORE: /home/bandaru/Templates
        run: |
            $BAR_CREATION -data /root -b $BAR_STORE/Rest_Api_Application_Put_Get.bar -a Rest_Api_Application_Put_Get   
             
      - name: oc login
        run: |
             cd /usr/local/bin/ 
             ./oc login --token=sha256~BPsuJLVUsxnpAgLbwYg10egcmDfqWoJklnPZuA847sY --server=https://c104-e.us-east.containers.cloud.ibm.com:31739
             ./oc project cp4i
             ./oc create -f cp4i.yaml
